[package]
name = "ngx-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.65"

[dependencies]
widestring = "1"
libc = "0.2"
ash = "*"
log = "0.4"
